### ISSUE TITLE
why we need fuse?

### ISSUE THREAD

**Issue by ZYecho** [Mic92/cntr#9]
1. why we need fuse support? if I created a new mount namespace, add I mount the slim container filesystem in /var/lib/cntr and mount debugging tool (whatever located in host or container) in /usr/bin/, everything seems ok, why need fuse? why redirect request between them? 
2. furthermore, I did't know why UnionFS is not good? I think it can also expand the slim container at run-time, but the paper says "However, in practice, users still end up with multiple base images due to the use of different base image distributions across different containers", the question is that with using cntr, this question is solved? in production environment, different application (java php...) of course have different base images?
3. int step#3, why at begins mount at TMP/ and chroot into /? Because it was in a new nested namespace, what happens if I mount at / at begins?
4. How to with IPC namespace? in step#3, after you bind mount /proc, you set this process in application ipc namespace? in this paper, the term 'namespace' only refer to the mount namespace? This also confused me a lot.
5. when I use cntr attach pid , I saw the cntr forks two child process, can you explain the purpose of them? I know one of them attach to application containers, create nested namespace, finally chroot /.

Thanks for your reply.

**Comment by ZYecho** [comment]
furthermore, I did't know why UnionFS is not good? I think it can also expand the slim container at run-time, but the paper says "However, in practice, users still end up with multiple base images due to the use of different base image distributions across different containers",  the question is that with using cntr, this question is solved?  in production environment,  different application (java php...) of course have different base images?

**Comment by ZYecho** [comment]
int step#3, why at begins mount at TMP/ and chroot into /? Because it was in a new nested namespace, what happens if I mount at / at begins?

**Comment by ZYecho** [comment]
How to with IPC namespace? in step#3, after you bind mount  /proc, you set this process in application ipc namespace?  in this paper, the term 'namespace' only refer to the mount namespace?  This also confused me a lot.

**Comment by ZYecho** [comment]
when I use cntr attach pid , I saw the cntr forks two child process, can you explain the purpose of them? I konw one of them was attach to application containers, create nested namespace, finally chroot.

**Comment by ZYecho** [comment]
@Mic92

**Comment by Mic92** [comment]
1. The filesystem layout is created by the container engine and not only consists of the filesystem image but also filesystems that purely exists in memory (procfs, devtempfs, tmpfs, sysfs) or those that cannot be mounted a second time (i.e. overlayfs, zfs and all fuse filesystems). Each implementation (lxc, docker, lxd, systemd-nspawn) also has supports multiple storage backends that all would be needed to reverse-engineered and maintained to achieve the same. Using a fuse is an approach that works with all current container implementation without any modification to their runtimes.
2. Sharing of files breaks if the applications are build from the same base image (let's say ubuntu) but from different versions (base images are often updated every day).
3. If cntrfs is mounted to `/` in the first place, it shadows the slim containers filesystem, which would make bind mounts impossible.
4. We support all namespaces https://github.com/Mic92/cntr/blob/master/src/namespace.rs#L10 However did not went into detail because applying them did not involve any special adaption.
5. The second child comes from rust's Command module: https://github.com/Mic92/cntr/blob/master/src/cmd.rs#L107 you should see an `execve` in strace for that child.

**Comment by ZYecho** [comment]
Thanks for your reply, close this issue.
